spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.94.135:7001
        - 192.168.94.135:7002
        - 192.168.94.135:7003
        - 192.168.94.135:7004
        - 192.168.94.135:7005
        - 192.168.94.135:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 商城首页分类菜单
PROTAL_CATRESULT_REDIS_KEY : PROTAL_CATRESULT_REDIS_KEY