server:
  port: 8101
spring:
  application:
    name: usian-cart-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#购物车
CART_COOKIE_KEY: CART_COOKIE_KEY
CART_COOKIE_EXPIRE: 604800